


- name: "Download Lib Files | Download Python Version {{ python_version }} to {{ base_file_dir }}"
  get_url:
    url: "{{ python_download_link }}"
    dest: "{{ base_file_dir }}"
  delegate_to: localhost