---
# defaults file for BaseInstall

base_file_dir: "{{ playbook_dir }}/roles/BaseInstall/files"

python_main_version: 3.6
python_version: "{{ python_main_version }}.3"

python_download_link: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"

