---
# defaults file for BaseInstall

base_file_dir: "{{ playbook_dir }}/roles/BaseInstall/files"


python_version: 3.6.3

python_download_link: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"

