---
# defaults file for BaseInstall

base_file_dir: "{{ playbook_dir }}/roles/BaseInstall/files"

python_main_version: 3.6 # Example 3.5.X
python_version: "{{ python_main_version }}.4" # example X.X.3

python_download_link: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"



## Add python packages you want installed in the list below to Base Python Interpter
## ex. python_lib_list: [ansible,sshuttle,requests]
python_lib_list_to_Install: [ansible,Fabric3,PyMySQL,paramiko,pexpect,XlsxWriter,requests,'requests[security]',pywinrm,'pywinrm[kerberos]',
'pywinrm[credssp]',sshuttle,arrow,pandas,tqdm,gnureadline,'mysqlpy==2.1.7']

## Add python packages you want installed in the list below to Python Virtual Enviroment
## ex. python_lib_list: [ansible,sshuttle,requests]
python_lib_list_to_Venv: ["sleekxmpp==1.3.1"]



python_lib_list: "{{ python_lib_list_to_Install }} + {{ python_lib_list_to_Venv }}"
