---
# defaults file for BaseInstall

base_file_dir: "{{ playbook_dir }}/roles/BaseInstall/files"

python_main_version: 3.6 # Example 3.5.X
python_version: "{{ python_main_version }}.4" # example X.X.3

python_download_link: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"



## Add python packages you want installed in the list below
## ex. python_lib_list: [ansible,sshuttle,requests]
python_lib_list: [ansible,Fabric3,PyMySQL,paramiko,pexpect,XlsxWriter,requests,'requests[security]',pywinrm,'pywinrm[kerberos]',
'pywinrm[credssp]',sshuttle,arrow,pandas,tqdm,gnureadline]

